// import TextField from '@components/Inputs/TextField';
import SideNav from '@/widgets/Sidenav';
import { Counter } from '@features/Counter';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>GateForce | Merchant Portal</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <h3 className="text-red-600">Hello World</h3>
      <SideNav />
    </div>
  );
};

export default Home;
